import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Navbar from "@/components/navbar";
import { PageLayout, ThemeProvider, Toaster } from "@edge-ui/react";
// import { UserProvider } from "@/lib/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Toaster />
          {/* <UserProvider>  */}
          <PageLayout>
            <Header />
            <Navbar />
            {children}
          </PageLayout>
          {/* </UserProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
